# The Conda environment specification for wav2sleep
name: wav2sleep
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2.2
  - pytorch-cuda=11.8
  - lightning~=2.1.0
  - torchvision
  # Useful
  - htop
  - tmux
  - ruby
  # Jupyter
  - jupyterlab~=4.0
  - ipympl
  - pip
  - pip:
# Core pip packages
    - -r requirements.txt
# Linting and development
    - -r requirements_dev.txt
