# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html#lightning.pytorch.callbacks.ModelCheckpoint
checkpointer:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  filename: '{epoch:02d}-{val_loss:.2f}'
  monitor: val_loss
  verbose: False
  save_last: True
  save_top_k: 1
  save_weights_only: False
  mode: 'min'
  every_n_epochs: 1
